### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by scoobie** [andrespp/docker-pdi#4]
I have a small doubt as I am new with Docker and containers.
You have a docker-compose file so if  I run docker-compose up, I see that two containers are running, so how I can execute the job, transformation when it is running? With the command that you supply to run jobs and transformations runs and stops right away no? Another doubt is: If I use on my transformation a postgresql database, the container with postgres must be running all the time so i need to put it on my docker-compose file.

**Comment by andrespp** [comment]
Hi Scoobie,

> You have a docker-compose file so if I run docker-compose up, I see that two containers are running, so how I can execute the job, transformation when it is running? 

Actually, this compose file is not supposed to there since this image is meant to be used to run spot jobs and transformations via command line, or to run PDIs user interface. Will fix it, thanks for pointing it out.

> the command that you supply to run jobs and transformations runs and stops right away no?

Yes, it stops after the transformation or job is completes running. You can also run the user interface with the following command:

```
$ docker run -it --rm -v /tmp/.X11-unix/:/tmp/.X11-unix/:ro \
        -v $(pwd):/jobs \
        -e XAUTH=$(xauth list|grep `uname -n` | cut -d ' ' -f5) -e "DISPLAY" \
        --name spoon \
        andrespp/pdi spoon
```

> If I use on my transformation a postgresql database, the container with postgres must be running all the time so i need to put it on my docker-compose file.

Yes, any database you need on your transformations must be running and accessible
